export {
  createElement,
  cloneElement,
  isValidElement,
  createRef,
  jsx,
  jsxs,
  Fragment,
  StrictMode,
  Suspense,
  Profiler,
  memo,
  forwardRef,
  lazy,
  Children,
  createPortal,
} from './vnode.js'
export {
  useState,
  useReducer,
  useEffect,
  useLayoutEffect,
  useInsertionEffect,
  useRef,
  useMemo,
  useCallback,
  useContext,
  useId,
  useImperativeHandle,
  useSyncExternalStore,
  useTransition,
  useDeferredValue,
  use,
  startTransition,
  createContext,
} from './hooks.js'
export { createRoot, hydrateRoot, flushSync } from './render.js'
export type { VNode, Props } from './vnode.js'
export type {
  Key,
  ReactNode,
  ReactElement,
  SetStateAction,
  Dispatch,
  DependencyList,
  EffectCallback,
  Ref,
  RefObject,
  MutableRefObject,
  RefCallback,
  PropsWithChildren,
  PropsWithRef,
  FC,
  FunctionComponent,
  ComponentType,
  ComponentProps,
  ContextType,
  Reducer,
  CSSProperties,
  ChangeEvent,
  FormEvent,
  MouseEventHandler,
  ChangeEventHandler,
  FormEventHandler,
  KeyboardEventHandler,
  HTMLAttributes,
  InputHTMLAttributes,
  JSX,
} from './types.js'

/** Reported to libraries that branch on the React 19 client API. */
export const version = '19.0.0-rinlay'

import {
  Children,
  Fragment,
  Profiler,
  StrictMode,
  Suspense,
  cloneElement,
  createElement,
  createPortal,
  createRef,
  forwardRef,
  isValidElement,
  lazy,
  memo,
} from './vnode.js'
import {
  createContext,
  startTransition,
  use,
  useCallback,
  useContext,
  useDeferredValue,
  useEffect,
  useId,
  useImperativeHandle,
  useInsertionEffect,
  useLayoutEffect,
  useMemo,
  useReducer,
  useRef,
  useState,
  useSyncExternalStore,
  useTransition,
} from './hooks.js'
import { createRoot, flushSync, hydrateRoot } from './render.js'

const React = {
  version,
  createElement,
  cloneElement,
  isValidElement,
  createRef,
  Fragment,
  StrictMode,
  Suspense,
  Profiler,
  memo,
  forwardRef,
  lazy,
  Children,
  createContext,
  createPortal,
  createRoot,
  hydrateRoot,
  flushSync,
  useState,
  useReducer,
  useEffect,
  useLayoutEffect,
  useInsertionEffect,
  useRef,
  useMemo,
  useCallback,
  useContext,
  useId,
  useImperativeHandle,
  useSyncExternalStore,
  useTransition,
  useDeferredValue,
  use,
  startTransition,
}

export default React
